const userdata = [
  {
    name: "Warden",
    lastname: "Soppit",
    phone: "3586575813",
    email: "wsoppit0@engadget.com",
    address: "2nd Floor",
    zipcode: "66006",
    country: "Egypt",
    city: "Jirjā",
    pass: "4",
    isadmin: true,
  },
  {
    name: "Wallas",
    lastname: "Cammell",
    phone: "6095176315",
    email: "wcammell1@mapy.cz",
    address: "Room 1283",
    zipcode: "1",
    country: "Egypt",
    city: "Kafr ad Dawwār",
    pass: "2",
    isadmin: true,
  },
  {
    name: "Janos",
    lastname: "Feben",
    phone: "4218512622",
    email: "jfeben2@jimdo.com",
    address: "Suite 1",
    zipcode: "12",
    country: "Egypt",
    city: "Ibshawāy",
    pass: "7",
    isadmin: false,
  },
  {
    name: "Nikos",
    lastname: "Kearle",
    phone: "3268847761",
    email: "nkearle3@cpanel.net",
    address: "15th Floor",
    zipcode: "96207",
    country: "Egypt",
    city: "Awsīm",
    pass: "3393",
    isadmin: false,
  },
  {
    name: "Griffith",
    lastname: "Scough",
    phone: "5074678397",
    email: "gscough4@opera.com",
    address: "PO Box 3927",
    zipcode: "726",
    country: "Egypt",
    city: "Bilqās",
    pass: "39",
    isadmin: false,
  },
  {
    name: "Franchot",
    lastname: "Gascone",
    phone: "8076463446",
    email: "fgascone5@about.me",
    address: "PO Box 45626",
    zipcode: "820",
    country: "Egypt",
    city: "At Tall al Kabīr",
    pass: "063",
    isadmin: true,
  },
  {
    name: "Lyell",
    lastname: "Wildsmith",
    phone: "9558504612",
    email: "lwildsmith6@symantec.com",
    address: "Apt 1333",
    zipcode: "8",
    country: "Egypt",
    city: "Qalyūb",
    pass: "82",
    isadmin: false,
  },
  {
    name: "Boothe",
    lastname: "Slemmonds",
    phone: "6024704743",
    email: "bslemmonds7@salon.com",
    address: "3rd Floor",
    zipcode: "2624",
    country: "Egypt",
    city: "Samannūd",
    pass: "51",
    isadmin: true,
  },
  {
    name: "Thane",
    lastname: "Songist",
    phone: "6113000677",
    email: "tsongist8@tuttocitta.it",
    address: "Apt 1776",
    zipcode: "47",
    country: "Egypt",
    city: "Diyarb Najm",
    pass: "117",
    isadmin: true,
  },
  {
    name: "Domenic",
    lastname: "Rosenblum",
    phone: "6425516386",
    email: "drosenblum9@freewebs.com",
    address: "Apt 447",
    zipcode: "4",
    country: "Egypt",
    city: "Ţāmiyah",
    pass: "401",
    isadmin: true,
  },
];

module.exports = userdata;
// name: 'John',
// lastName: 'Doe',
// email: 'john@doe.com',
// password: bcrypt.hashSync('john@doe.com', 10),
